/** The CSS named colours, as display names. A CSS name is its display name
 *  with the spaces removed and lower-cased ("Cornflower blue" →
 *  `cornflowerblue`), so each colour is written once. `grey` names also
 *  answer to the `gray` spelling, and Aqua/Cyan and Fuchsia/Magenta are
 *  the same colour under two names. `transparent` and `currentcolor` are
 *  not colours the picker can show, so they are left out. */
export const CSS_COLOUR_NAMES: readonly (readonly [name: string, hex: string])[] = [
  ['Alice blue', '#f0f8ff'],
  ['Antique white', '#faebd7'],
  ['Aqua', '#00ffff'],
  ['Aquamarine', '#7fffd4'],
  ['Azure', '#f0ffff'],
  ['Beige', '#f5f5dc'],
  ['Bisque', '#ffe4c4'],
  ['Black', '#000000'],
  ['Blanched almond', '#ffebcd'],
  ['Blue', '#0000ff'],
  ['Blue violet', '#8a2be2'],
  ['Brown', '#a52a2a'],
  ['Burlywood', '#deb887'],
  ['Cadet blue', '#5f9ea0'],
  ['Chartreuse', '#7fff00'],
  ['Chocolate', '#d2691e'],
  ['Coral', '#ff7f50'],
  ['Cornflower blue', '#6495ed'],
  ['Cornsilk', '#fff8dc'],
  ['Crimson', '#dc143c'],
  ['Cyan', '#00ffff'],
  ['Dark blue', '#00008b'],
  ['Dark cyan', '#008b8b'],
  ['Dark goldenrod', '#b8860b'],
  ['Dark grey', '#a9a9a9'],
  ['Dark green', '#006400'],
  ['Dark khaki', '#bdb76b'],
  ['Dark magenta', '#8b008b'],
  ['Dark olive green', '#556b2f'],
  ['Dark orange', '#ff8c00'],
  ['Dark orchid', '#9932cc'],
  ['Dark red', '#8b0000'],
  ['Dark salmon', '#e9967a'],
  ['Dark sea green', '#8fbc8f'],
  ['Dark slate blue', '#483d8b'],
  ['Dark slate grey', '#2f4f4f'],
  ['Dark turquoise', '#00ced1'],
  ['Dark violet', '#9400d3'],
  ['Deep pink', '#ff1493'],
  ['Deep sky blue', '#00bfff'],
  ['Dim grey', '#696969'],
  ['Dodger blue', '#1e90ff'],
  ['Firebrick', '#b22222'],
  ['Floral white', '#fffaf0'],
  ['Forest green', '#228b22'],
  ['Fuchsia', '#ff00ff'],
  ['Gainsboro', '#dcdcdc'],
  ['Ghost white', '#f8f8ff'],
  ['Gold', '#ffd700'],
  ['Goldenrod', '#daa520'],
  ['Grey', '#808080'],
  ['Green', '#008000'],
  ['Green yellow', '#adff2f'],
  ['Honeydew', '#f0fff0'],
  ['Hot pink', '#ff69b4'],
  ['Indian red', '#cd5c5c'],
  ['Indigo', '#4b0082'],
  ['Ivory', '#fffff0'],
  ['Khaki', '#f0e68c'],
  ['Lavender', '#e6e6fa'],
  ['Lavender blush', '#fff0f5'],
  ['Lawn green', '#7cfc00'],
  ['Lemon chiffon', '#fffacd'],
  ['Light blue', '#add8e6'],
  ['Light coral', '#f08080'],
  ['Light cyan', '#e0ffff'],
  ['Light goldenrod yellow', '#fafad2'],
  ['Light grey', '#d3d3d3'],
  ['Light green', '#90ee90'],
  ['Light pink', '#ffb6c1'],
  ['Light salmon', '#ffa07a'],
  ['Light sea green', '#20b2aa'],
  ['Light sky blue', '#87cefa'],
  ['Light slate grey', '#778899'],
  ['Light steel blue', '#b0c4de'],
  ['Light yellow', '#ffffe0'],
  ['Lime', '#00ff00'],
  ['Lime green', '#32cd32'],
  ['Linen', '#faf0e6'],
  ['Magenta', '#ff00ff'],
  ['Maroon', '#800000'],
  ['Medium aquamarine', '#66cdaa'],
  ['Medium blue', '#0000cd'],
  ['Medium orchid', '#ba55d3'],
  ['Medium purple', '#9370db'],
  ['Medium sea green', '#3cb371'],
  ['Medium slate blue', '#7b68ee'],
  ['Medium spring green', '#00fa9a'],
  ['Medium turquoise', '#48d1cc'],
  ['Medium violet red', '#c71585'],
  ['Midnight blue', '#191970'],
  ['Mint cream', '#f5fffa'],
  ['Misty rose', '#ffe4e1'],
  ['Moccasin', '#ffe4b5'],
  ['Navajo white', '#ffdead'],
  ['Navy', '#000080'],
  ['Old lace', '#fdf5e6'],
  ['Olive', '#808000'],
  ['Olive drab', '#6b8e23'],
  ['Orange', '#ffa500'],
  ['Orange red', '#ff4500'],
  ['Orchid', '#da70d6'],
  ['Pale goldenrod', '#eee8aa'],
  ['Pale green', '#98fb98'],
  ['Pale turquoise', '#afeeee'],
  ['Pale violet red', '#db7093'],
  ['Papaya whip', '#ffefd5'],
  ['Peach puff', '#ffdab9'],
  ['Peru', '#cd853f'],
  ['Pink', '#ffc0cb'],
  ['Plum', '#dda0dd'],
  ['Powder blue', '#b0e0e6'],
  ['Purple', '#800080'],
  ['Rebecca purple', '#663399'],
  ['Red', '#ff0000'],
  ['Rosy brown', '#bc8f8f'],
  ['Royal blue', '#4169e1'],
  ['Saddle brown', '#8b4513'],
  ['Salmon', '#fa8072'],
  ['Sandy brown', '#f4a460'],
  ['Sea green', '#2e8b57'],
  ['Seashell', '#fff5ee'],
  ['Sienna', '#a0522d'],
  ['Silver', '#c0c0c0'],
  ['Sky blue', '#87ceeb'],
  ['Slate blue', '#6a5acd'],
  ['Slate grey', '#708090'],
  ['Snow', '#fffafa'],
  ['Spring green', '#00ff7f'],
  ['Steel blue', '#4682b4'],
  ['Tan', '#d2b48c'],
  ['Teal', '#008080'],
  ['Thistle', '#d8bfd8'],
  ['Tomato', '#ff6347'],
  ['Turquoise', '#40e0d0'],
  ['Violet', '#ee82ee'],
  ['Wheat', '#f5deb3'],
  ['White', '#ffffff'],
  ['White smoke', '#f5f5f5'],
  ['Yellow', '#ffff00'],
  ['Yellow green', '#9acd32'],
];

/** `cornflowerblue` / `darkgray` → hex, or null. */
export function cssNamedColour(cssName: string): string | null {
  return CSS_NAME_TO_HEX.get(cssName.toLowerCase()) ?? null;
}

/** The CSS spelling of a display name: `Dark slate grey` → `darkslategrey`. */
export const cssNameOf = (name: string) => name.replace(/\s+/g, '').toLowerCase();

const CSS_NAME_TO_HEX = new Map<string, string>();
for (const [name, hex] of CSS_COLOUR_NAMES) {
  const css = cssNameOf(name);
  CSS_NAME_TO_HEX.set(css, hex);
  if (css.includes('grey')) CSS_NAME_TO_HEX.set(css.replace('grey', 'gray'), hex);
}
